spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: db
    password: pass
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update